name: CI/CD Pipeline

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

env:
  HF_SPACE: ${{ secrets.HF_USERNAME }}
  HF_TOKEN: ${{ secrets.HF_TOKEN }}

jobs:
  # Job 1: Tests
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
    
    - name: Set up Python
      run: uv python install 3.13
    
    - name: Install dependencies
      run: |
        uv sync --all-extras
    
    - name: Run unit tests
      run: |
        uv run pytest tests/ -v \
          --cov=api \
          --cov=src \
          --cov-report=xml \
          --cov-report=term-missing
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      if: always()
      with:
        file: ./coverage.xml
        fail_ci_if_error: false

    
# Job 2: Deploy to Hugging Face Spaces
  deploy:
    name: Deploy to Hugging Face Spaces
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install hub
      run: pip install huggingface_hub

    - name: Prepare deploy folder
      run: |
            mkdir -p deploy/
            mkdir -p deploy/api
            mkdir -p deploy/data
            mkdir -p deploy/gradio_app
            mkdir -p deploy/src
            cp Dockerfile deploy/
            cp pyproject.toml deploy/
            cp api/api.py deploy/api
            cp gradio_app/app.py deploy/gradio_app
            cp src/* deploy/src


    - name: Upload to Space
      env:
       HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
          python << 'EOF'
          from huggingface_hub import HfApi
          import os

          api = HfApi()

          # upload_folder avec filtres
          api.upload_folder(
              folder_path="deploy",
              repo_id="0biyohan/Projet_8",
              repo_type="space",
              ignore_patterns=[
                  ".git/**",
                  ".github/**",
                  "__pycache__/**",
                  "*.pyc",
                  "tests/**",
                  "README.dev.md",
              ],
          )
          EOF